# Generated by Django 5.0.1 on 2024-01-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('FIC', 'Fiction'), ('NFIC', 'Non-Fiction'), ('FAN', 'Fantasy'), ('ROM', 'Romance'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('HOR', 'Horror'), ('HIS', 'History')], max_length=4),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('FIC', 'Fiction'), ('NFIC', 'Non-Fiction'), ('FAN', 'Fantasy'), ('ROM', 'Romance'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('HOR', 'Horror'), ('HIS', 'History')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
