# Generated by Django 5.0.1 on 2024-01-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_genre_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NFIC', 'Non-Fiction'), ('FAN', 'Fantasy'), ('ROM', 'Romance'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('HOR', 'Horror'), ('HIS', 'History')], max_length=4),
        ),
    ]
