# Generated by Django 5.0.1 on 2024-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_fav_author_alter_userprofile_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NFIC', 'Non-Fiction'), ('FAN', 'Fantasy'), ('ROM', 'Romance'), ('MYS', 'Mystery'), ('SCI', 'Science Fiction'), ('HOR', 'Horror'), ('HIS', 'History')], max_length=4),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
