# Generated by Django 5.0.1 on 2024-01-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_books_genre_books_gnere_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='gnere',
            new_name='genre',
        ),
    ]
